{{- if .Values.cosign.cosignPub }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "policy-controller.labels" . | nindent 4 }}
  name: {{ template "policy-controller.fullname" . }}-cosign-key
  namespace: {{ .Release.Namespace }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  cosign.pub: {{ .Values.cosign.cosignPub}}
{{- end -}}
