{{ if .Values.webhook.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "policy-controller.fullname" . }}-webhook
  labels:
    {{- include "policy-controller.labels" . | nindent 4 }}
    control-plane: {{ template "policy-controller.fullname" . }}-webhook
{{- if .Values.labels }}
{{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
  annotations:
{{- if .Values.annotations }}
{{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
spec:
  minAvailable: {{ .Values.webhook.podDisruptionBudget.minAvailable }}
  maxUnavailable: {{ .Values.webhook.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "policy-controller.selectorLabels" . | nindent 6 }}
      control-plane: {{ template "policy-controller.fullname" . }}-webhook
{{- end }}
