apiVersion: v2
name: updatetree
description: Update the status of an existing Trillian tree

type: application

version: 0.0.5
appVersion: 0.6.7


keywords:
  - security
  - trillian
  - updatetree

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: updatetree
      image: ghcr.io/sigstore/scaffolding/updatetree:v0.6.7@sha256:357cf3545cd459634fe6a461a7690bc5f425c353e48c80da551cfec6887d627d
