apiVersion: v2
name: rekor
description: Part of the sigstore project, Rekor is a timestamping server and transparency log for storing signatures, as well as an API based server for validation

type: application

version: 1.3.8
appVersion: 1.3.0

keywords:
  - security
  - transparency logs

home: https://sigstore.dev/
sources:
  - https://github.com/sigstore/rekor
maintainers:
  - name: The Sigstore Authors

dependencies:
  - name: trillian
    version: 0.2.12
    repository: https://sigstore.github.io/helm-charts
    condition: trillian.enabled

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: createtree
      image: ghcr.io/sigstore/scaffolding/createtree:v0.6.7@sha256:8e921d028b46d5ad98994d58f79e2724cf84e99e3270f5799fe0f1a6b518bc4e
    - name: curlimages/curl
      image: docker.io/curlimages/curl@sha256:dca6e1b1c8e7b8b8e7be4e79fc78a858d12fd56245cb31bfa281dbf7c73a6498
    - name: rekor-server
      image: gcr.io/projectsigstore/rekor-server:v1.3.0@sha256:1cf8618112dd67113a49c93f717488e45c5fc765eb03484870123404d9e9f00c
    - name: redis
      image: docker.io/redis@sha256:6c42cce2871e8dc5fb3e843ed5c4e7939d312faf5e53ff0ff4ca955a7e0b2b39
    - name: backfill-redis
      image: gcr.io/projectsigstore/backfill-redis:v1.3.0@sha256:9977c7b99586fad13a4d1cba9d17b011e3de4926a9e02b9873fd872fe31ce2f3
